"""Add authentication tables

Revision ID: bdbcb0969e9a
Revises: e0d2e787dba4
Create Date: 2025-03-15 16:34:55.585820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbcb0969e9a'
down_revision = 'e0d2e787dba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
